# Generated by Django 4.2.17 on 2024-12-18 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_or_member', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_group_min', models.IntegerField()),
                ('age_group_max', models.IntegerField(default=99)),
                ('duration', models.IntegerField(choices=[(15, '15 Minutes'), (30, '30 Minutes'), (45, '45 Minutes'), (60, '1 Hour'), (75, '1 Hour 15 Minutes'), (90, '1 Hour 30 Minutes'), (105, '1 hour 45 Minutes'), (120, '2 Hours'), (135, '2 Hours 15 Minutes'), (150, '2 Hours 30 Minutes'), (165, '2 Hours 45 Minutes'), (180, '3 Hours'), (195, '3 Hours 15 Minutes'), (210, '3 Hours 30 Minutes'), (225, '3 Hours 45 Minutes'), (240, '4 Hours'), (255, '4 Hours 15 Minutes'), (270, '4 Hours 30 Minutes'), (285, '4 Hours 45 Minutes'), (300, '5 Hours')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('default_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('is_member', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('selected_days', models.JSONField(default=list, help_text="Store selected days of the week as a JSON array (e.g., ['MON', 'TUE'])")),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_date', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('capacity', models.IntegerField(verbose_name=0)),
                ('attendees', models.ManyToManyField(to='dashboard.booking')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.classtype')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.classinstance'),
        ),
        migrations.AddField(
            model_name='booking',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.participant'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
