# Generated by Django 4.2.17 on 2024-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_participant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='add las name', max_length=200),
            preserve_default=False,
        ),
    ]
