# Generated by Django 4.2.17 on 2025-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_timetable_selected_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='selected_days',
            field=models.JSONField(blank=True, help_text="Store selected days of the week as a JSON array (e.g., ['MON', 'TUE'])", null=True, verbose_name='selected_days'),
        ),
    ]
