# Generated by Django 4.2.17 on 2025-01-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_timetable_selected_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinstance',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='day', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classinstance',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
