# Generated by Django 4.2.17 on 2025-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_classinstance_day_alter_classinstance_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinstance',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classinstance',
            name='instance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classinstance',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
