# Generated by Django 4.2.17 on 2025-01-06 18:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_classinstance_finish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='color_value',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
