# Generated by Django 4.2.17 on 2025-01-07 18:04

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='£', max_length=5)),
                ('brand_colour_1', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('brand_colour_2', colorfield.fields.ColorField(default='#00FF00', image_field=None, max_length=25, samples=None)),
                ('brand_colour_3', colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=25, samples=None)),
                ('default_country', models.CharField(default='United Kingdom', max_length=200)),
                ('default_language', models.CharField(default='English', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('custom_font', models.CharField(default='Arial', max_length=200)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('site_title', models.CharField(default='Open Club Manager', max_length=200)),
                ('site_tagline', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
