# Generated by Django 4.2.17 on 2025-01-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customization',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customization',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
