# Generated by Django 4.2.17 on 2025-01-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_customization_smtp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='confirmation_message',
            field=models.CharField(default='See you soon!', max_length=200),
        ),
    ]
