# Generated by Django 4.2.17 on 2025-01-09 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_customization_confirmation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='brand_colour_1',
            new_name='brand_color_1',
        ),
        migrations.RenameField(
            model_name='customization',
            old_name='brand_colour_2',
            new_name='brand_color_2',
        ),
        migrations.RenameField(
            model_name='customization',
            old_name='brand_colour_3',
            new_name='brand_color_3',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
