# Generated by Django 4.2.17 on 2025-01-09 10:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_brand_colour_1_customization_brand_color_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='brand_color_1',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='customization',
            name='brand_color_2',
            field=colorfield.fields.ColorField(blank=True, default='#00FF00', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='customization',
            name='brand_color_3',
            field=colorfield.fields.ColorField(blank=True, default='#0000FF', image_field=None, max_length=25, samples=None),
        ),
    ]
