# Generated by Django 4.2.17 on 2025-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_customization_brand_color_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='business_name',
            field=models.CharField(default='Open Club Manager'),
        ),
    ]
