# Generated by Django 4.2.17 on 2025-01-09 13:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_customization_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='brand_color_dark',
            field=colorfield.fields.ColorField(blank=True, default='#061A40', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='customization',
            name='brand_color_white',
            field=colorfield.fields.ColorField(blank=True, default='#f8f9fb', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='customization',
            name='brand_color_1',
            field=colorfield.fields.ColorField(blank=True, default='#AECBEB', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='customization',
            name='brand_color_2',
            field=colorfield.fields.ColorField(blank=True, default='#71A5DE', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='customization',
            name='brand_color_3',
            field=colorfield.fields.ColorField(blank=True, default='#0353A4', image_field=None, max_length=25, samples=None),
        ),
    ]
