# Generated by Django 4.2.17 on 2025-01-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_customization_favicon_alter_customization_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=200)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(choices=[('AUD', 'Australian Dollar'), ('BGN', 'Bulgarian Lev'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('EUR', 'Euro'), ('gbp', 'British Pound'), ('HKD', 'Hong Kong Dollar'), ('JPY', 'Japanese Yen'), ('MXN', 'Mexican Peso'), ('NOK', 'Norwegian Krone'), ('NZD', 'New Zealand Dollar'), ('PLN', 'Polish Złoty'), ('RON', 'Romanian Leu'), ('SEK', 'Swedish Krona'), ('SGD', 'Singapore Dollar'), ('USD', 'United States Dollar')], default='GBP', max_length=3)),
            ],
        ),
    ]
