# Generated by Django 4.2.17 on 2025-01-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_stripeintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='contact_address_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customization',
            name='contact_address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customization',
            name='contact_address_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customization',
            name='contact_address_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customization',
            name='contact_address_zip',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customization',
            name='contact_other',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
