# Generated by Django 4.2.17 on 2025-02-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_remove_customization_smtp_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classtype",
            name="members_only",
            field=models.BooleanField(default=False),
        ),
    ]
