# Generated by Django 4.2.17 on 2025-04-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_alter_customization_favicon_alter_customization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="classinstance",
            name="timetable_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.timetable",
            ),
            preserve_default=False,
        ),
    ]
