# Generated by Django 4.2.17 on 2025-04-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_classinstance_timetable_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classinstance",
            old_name="timetable_id",
            new_name="timetable",
        ),
    ]
