# Generated by Django 4.2.17 on 2025-04-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_rename_timetable_id_classinstance_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sms_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
